// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmjvsftlounkitclmzzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtanZzZnRsb3Vua2l0Y2xtenp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2ODYwMzIsImV4cCI6MjA4ODI2MjAzMn0.HRQIpcyPb8ZJTLPQ9GzceqnrmrRlVT-JqVkun-l5JrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});